language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm test

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm test -- --watchAll=false --coverage --coverageReporters=text-lcov | ./node_modules/coveralls/bin/coveralls.js
    - stage: build, serve & e2e testing
      node_js: node
      env:
        - CYPRESS_baseUrl=http://localhost:5000
      script:
        - cp src/config.sample.json src/config.json & npm run build
        - npm run mocked &
        - npm run serve &
        - npm run e2e:run
