language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm test

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm test -- --watchAll=false --coverage --coverageReporters=text-lcov | ./node_modules/coveralls/bin/coveralls.js
