version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: on-failure
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: host.docker.internal
            database: ojs2
            user: usr
            password: psw
            rawAccess: true
            port: '3306'
            migrations: false
